org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.69-beta
loader_version_range=[1,)
jei_version=29.5.0.26
jade_version=26.0.10+neoforge
curios_version=15.0.0-beta.2+26.1.2

mod_id=smallprogressions
mod_name=Small Progressions
mod_license=MIT
mod_version=0.0.9+mc-26.1.2
mod_group_id=com.misterd.smallprogressions
